#!/usr/bin/env bun
/**
 * Regenerate the parts of the Bloom skills that are derived from the Bloom API.
 *
 * Source of truth is the PUBLIC `@bloom/sdk` package (its published
 * `operation-manifest`). This script has NO access to, and no reference to, the
 * private Bloom monorepo — it only reads a public npm package. That keeps the
 * data flow public -> public (see the repo README "How this stays in sync").
 *
 * Usage:
 *   bun scripts/generate.ts                 # reads @bloom/sdk (CI / normal)
 *   MANIFEST_JSON=./manifest.json bun scripts/generate.ts   # local seed from a JSON file
 *
 * Output:
 *   skills/bloom-mcp/references/tools.md    # the tool catalog
 */
import { writeFileSync, readFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";

type Operation = {
  operationId: string;
  category: string;
  stability: string;
  visibility: string;
  description: string;
};
type Manifest = { version: number; operations: Operation[] };

async function loadManifest(): Promise<Manifest> {
  const local = process.env.MANIFEST_JSON;
  if (local) {
    return JSON.parse(readFileSync(resolve(local), "utf8")) as Manifest;
  }
  // Public package only. Never import from the private monorepo.
  const mod = await import("@bloom/sdk/generated/bloom-api/operation-manifest");
  return (mod as { operationManifest: Manifest }).operationManifest;
}

const CATEGORY_ORDER = ["auth", "discovery", "canvas", "agent", "comments"];
const CATEGORY_BLURB: Record<string, string> = {
  auth: "Confirm who you are and what you can reach.",
  discovery: "Orient: find the project, branch, and canvas pages to work in.",
  canvas: "Read and write **canvas frames** — React TSX at `@bloom-frame/<uuid>`, not host-repo files.",
  agent: "Hand off full-stack / codebase work to the Bloom agent on a branch.",
  comments: "Leave and read review comments anchored to frames.",
};

function render(manifest: Manifest): string {
  const ops = manifest.operations.filter((o) => o.visibility === "public");
  const byCat = new Map<string, Operation[]>();
  for (const o of ops) (byCat.get(o.category) ?? byCat.set(o.category, []).get(o.category)!).push(o);
  const cats = [...byCat.keys()].sort(
    (a, b) => (CATEGORY_ORDER.indexOf(a) + 1 || 99) - (CATEGORY_ORDER.indexOf(b) + 1 || 99)
  );

  const lines: string[] = [];
  lines.push("<!-- GENERATED by scripts/generate.ts from the public @bloom/sdk operation-manifest. Do not edit by hand. -->");
  lines.push("");
  lines.push("# Bloom MCP tool catalog");
  lines.push("");
  lines.push(
    `${ops.length} public tools, grouped by what they are for. Every tool is \`experimental\` — ` +
      "expect the surface to move. Full input/output schemas live in each tool's own JSON schema " +
      "(exposed by the MCP server); this file is the map, not the schema."
  );
  lines.push("");
  for (const cat of cats) {
    lines.push(`## ${cat}`);
    if (CATEGORY_BLURB[cat]) lines.push("");
    if (CATEGORY_BLURB[cat]) lines.push(CATEGORY_BLURB[cat]);
    lines.push("");
    for (const o of byCat.get(cat)!) {
      lines.push(`### \`${o.operationId}\``);
      lines.push("");
      lines.push(o.description.trim());
      lines.push("");
    }
  }
  return lines.join("\n");
}

async function main() {
  const manifest = await loadManifest();
  const out = resolve(import.meta.dir, "../skills/bloom-mcp/references/tools.md");
  mkdirSync(dirname(out), { recursive: true });
  writeFileSync(out, render(manifest) + "\n");
  console.log(`Wrote ${out} (${manifest.operations.length} operations)`);
}

main();
